language: python
python:
  - 2.7
notifications:
  email:
    recipients:
      - sdksupport@vantiv.com
    on_success: always
    on_failure: always
env:
 global:
   - BUILD_DIR=`pwd`
   - MP_CONFIG_DIR=$BUILD_DIR
   - PAYFAC_MP_SDK_CONFIG=$MP_CONFIG_DIR/.payfac_mp_sdk.conf
install:
   - pip install coverage
   - pip install codecov
   - python setup.py install
   - python $BUILD_DIR/tools/generate.py

script:
  - echo $BUILD_DIR
  - echo $PAYFAC_MP_SDK_CONFIG
  - cat $PAYFAC_MP_SDK_CONFIG
  - nosetests  $BUILD_DIR/test/unit $BUILD_DIR/test/functional -v --with-coverage
  
deploy:
  - provider: pypi
    user: $pypi_user
    password: $pypi_pass
    on:
     tags: true
  - provider: releases
    api_key: $GITHUB_TOKEN
    skip_cleanup: true
    on:
     tags: true

after_success:
     - bash <(curl -s https://codecov.io/bash)
