language: python
python:
  - 2.7
notifications:
  email:
    recipients:
      - sdksupport@vantiv.com
    on_success: always
    on_failure: always
    
install:
  - pip install codecov
  
  
env:
 global:
  - BUILD_DIR=`pwd`
  - MP_CONFIG_DIR=$BUILD_DIR
  - PAYFAC_MP_SDK_CONFIG=$BUILD_DIR/.payfac_mp_sdk.conf
    

  
script:
 - echo $BUILD_DIR
 - echo $PAYFAC_MP_SDK_CONFIG
 - echo "username":"USERNAME">$PAYFAC_MP_SDK_CONFIG
 - echo "password":"PASSWORD">>$PAYFAC_MP_SDK_CONFIG
 - echo "url":"https://www.testvantivcnp.com/sandbox/payfac">>$PAYFAC_MP_SDK_CONFIG
 - echo "neuter_xml":"false">>$PAYFAC_MP_SDK_CONFIG
 - cat $PAYFAC_MP_SDK_CONFIG
 - python setup.py install
 - python $BUILD_DIR/tools/generate.py
 - python -m coverage run test/*

# deploy:
#   provider: releases
#   api_key: $GITHUB_TOKEN
#   file_glob: true
#   file: build/kit/dist/*
#   skip_cleanup: true
#   on:
#     tags: true


after_success:
 - codecov
#  - bash <(curl -s https://codecov.io/bash)


